In [15]:
import pandas as pd

# Load your dataset
data = pd.read_csv("orders.csv", index_col = 0)

data.head()

,client,delivery_place,date,product,product_description,measure,quantity,is_internal_client,warehouse_zone,product_type,product_subtype
0,1128254,6346669,2023-01-06,126898,AGUA DAS PEDRAS SALGADAS 6x0.33 PET,UN,600.0,Não,AMB,Bebidas,Aguas Minerais
1,1001096,6001131,2023-01-03,126898,AGUA DAS PEDRAS SALGADAS 6x0.33 PET,UN,120.0,Não,AMB,Bebidas,Aguas Minerais
2,1001096,6001131,2023-01-17,126898,AGUA DAS PEDRAS SALGADAS 6x0.33 PET,UN,120.0,Não,AMB,Bebidas,Aguas Minerais
3,1121833,6358142,2023-01-04,126898,AGUA DAS PEDRAS SALGADAS 6x0.33 PET,UN,12.0,Não,AMB,Bebidas,Aguas Minerais
4,1122758,6328488,2023-01-04,126898,AGUA DAS PEDRAS SALGADAS 6x0.33 PET,UN,60.0,Não,AMB,Bebidas,Aguas Minerais

In [24]:
# Convert the 'date' column to a proper datetime format
data['date'] = pd.to_datetime(data['date'])

# Encode categorical columns using one-hot encoding or label encoding

# One-hot encoding
data2 = pd.get_dummies(data)

print(data2)

             date  quantity  product_0  product_1  product_2  product_3  \
0      2023-01-06     600.0          0          0          0          0
1      2023-01-03     120.0          0          0          0          0
2      2023-01-17     120.0          0          0          0          0
3      2023-01-04      12.0          0          0          0          0
4      2023-01-04      60.0          0          0          0          0
...           ...       ...        ...        ...        ...        ...
434415 2023-01-31       2.0          0          0          0          0
434416 2023-01-31       2.0          0          0          0          0
434417 2023-01-31       6.0          0          0          0          0
434418 2023-01-31       2.0          0          0          0          0
434419 2023-01-31       1.0          0          0          0          0

        product_4  product_5  product_6  product_7  ...  delivery_place_E75  \
0               0          0          0          0  ...                   0
1               0          0          0          0  ...                   0
2               0          0          0          0  ...                   0
3               0          0          0          0  ...                   0
4               0          0          0          0  ...                   0
...           ...        ...        ...        ...  ...                 ...
434415          0          0          0          0  ...                   0
434416          0          0          0          0  ...                   0
434417          0          0          0          0  ...                   0
434418          0          0          0          0  ...                   0
434419          0          0          0          0  ...                   0

        delivery_place_E76  delivery_place_E78  delivery_place_E79  \
0                        0                   0                   0
1                        0                   0                   0
2                        0                   0                   0
3                        0                   0                   0
4                        0                   0                   0
...                    ...                 ...                 ...
434415                   0                   0                   0
434416                   0                   0                   0
434417                   0                   0                   0
434418                   0                   0                   0
434419                   0                   0                   0

        delivery_place_E8  delivery_place_E88  delivery_place_E9  \
0                       0                   0                  0
1                       0                   0                  0
2                       0                   0                  0
3                       0                   0                  0
4                       0                   0                  0
...                   ...                 ...                ...
434415                  0                   0                  0
434416                  0                   0                  0
434417                  0                   0                  0
434418                  0                   0                  0
434419                  0                   0                  0

        delivery_place_E95  is_internal_client_Não  is_internal_client_Sim
0                        0                       1                       0
1                        0                       1                       0
2                        0                       1                       0
3                        0                       1                       0
4                        0                       1                       0
...                    ...                     ...                     ...
434415                   0                       0                       1
434416                   0                       0                       1
434417                   0                       0                       1
434418                   0                       0                       1
434419                   0                       0                       1

[434420 rows x 15346 columns]

In [26]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# Convert 'is_internal_client' column to binary values
data['is_internal_client'] = data['is_internal_client'].astype(int)

# Save the preprocessed data (optional)
data.to_csv("preprocessed_data.csv", index=False)

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

### Categorical data to be converted to numeric data
colors = (["red", "green", "yellow", "red", "blue"])

### integer mapping using LabelEncoder
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(colors)
print(integer_encoded)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)

### One hot encoding
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)

print(onehot_encoded)